server:
  port: 7001 # hostname:7001/ 访问eureka主页

#eureka配置
eureka:
  instance:
    hostname: localhost7001 #eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向eureka注册自己
    fetch-registry: false  #false表示自己为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #服务注册地址
      defaultZone: http://localhost:7002/eureka/
