server:
  port: 80

#eureka:
#  client:
#    register-with-eureka: false  #不向注册中心注册自己
#    service-url:
#      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/ #配置可访问集群，实现负载均衡
feign:
  hystrix:
    enabled: true #开启feign.hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7001/eureka/
  instance:
    instance-id: test-consumer-feign
    prefer-ip-address: true

spring:
  application:
    name: test-consumer-feign