Server:
  port: 8001
mybatis:
  type-aliases-package: com.booknet.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  application:
    name: test-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.100.10.67:3306/booknet?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: qiaomao